
import React from 'react';
import { ExerciseCard } from './ExerciseCard';
import type { WorkoutPlan } from '../types';

interface WorkoutPlanDisplayProps {
  plan: WorkoutPlan;
}

export const WorkoutPlanDisplay: React.FC<WorkoutPlanDisplayProps> = ({ plan }) => {
  return (
    <div className="mt-12 animate-fade-in">
      <h2 className="text-3xl md:text-4xl font-bold text-center text-white mb-2">
        Your <span className="text-red-500">Personalized</span> Workout
      </h2>
      <p className="text-center text-gray-400 mb-8">Generated by your AI Coach. Time to get to work!</p>
      <div className="space-y-4">
        {plan.map((exercise, index) => (
          <ExerciseCard key={index} exercise={exercise} index={index} />
        ))}
      </div>
    </div>
  );
};
